### ISSUE TITLE
スライド5 / 注視点が必要かどうか

### ISSUE THREAD

**Issue by temochiz-lab** [temochiz-lab/yanokura-2022#11]
心拍数測定中だと思うのですが、この画面は必要でしょうか？
測定にかかる時間がわからないので、もし必要であれば「次へ」ボタンを付けるか、何かキーを押すかになります。
画面を見て作業をするわけではないので、ブランクで良いような気も。

**Comment by Yanokura-TOKIWA** [comment]
実験中に画面を見続けてもらうことに併せ、心拍数計測中にも画面を見た状態でいてもらおうと考えています。
注視点がある方が見る場所がはっきりと分かるかなと思い、こちらの画面を入れました。
キー押しでの画面遷移を想定しております。

**Comment by temochiz-lab** [comment]
必要である旨、了解しました。
他の画面はボタンで遷移していますが、この画面だけキーで遷移にしますか？
その場合、「何かキーを押して次の画面になります」など表示も必要かなと思います。

**Comment by Yanokura-TOKIWA** [comment]
スライド4～5の操作は実験者が行うことを想定しているので、特に表記は必要ないと考えています。

**Comment by temochiz-lab** [comment]
こちらは、誤操作しないように特定のキーにしておくのと、どのキーでも押せば遷移するのと、どちらが良いでしょうか？

**Comment by Yanokura-TOKIWA** [comment]
では誤操作を防げるよう特定のキーの方で、Qキーでお願いしたく思います。

**Comment by temochiz-lab** [comment]
了解しましたー
