### ISSUE TITLE
スライド7 / 実際に音声を再生するかどうか

### ISSUE THREAD

**Issue by temochiz-lab** [temochiz-lab/yanokura-2022#12]
ここは説明だけでしょうか？
実際に音声を再生して自動で次の画面への切り替えでしょうか？

**Comment by Yanokura-TOKIWA** [comment]
音声は無しで説明の文言のみと考えています。
音を鳴らさないため、画面の切り替えはキー押しで行いたく思います。

**Comment by temochiz-lab** [comment]
であれば、
「何かキーを押すと次の画面に進みます」
の一文を入れておきましょうか？

**Comment by Yanokura-TOKIWA** [comment]
一文ある方が良いですね。お願いいたします。

**Comment by temochiz-lab** [comment]
了解しました。　チケットクローズしておきます。
