### ISSUE TITLE
練習で使用する音声の速度について

### ISSUE THREAD

**Issue by temochiz-lab** [temochiz-lab/yanokura-2022#14]
テンポAが、1.0で、Bはそれ以外のもの2つですよね？
この2つな何倍速のものを使いましょうか。

**Comment by Yanokura-TOKIWA** [comment]
Aについてはその通りで1.0倍です。
Bは、練習1では0.5倍、練習2では1.5倍のものにしていただきたく思います。

**Comment by temochiz-lab** [comment]
了解しました。
