### ISSUE TITLE
audio-button-responseのボタン位置が一番上にしか指定できない件

### ISSUE THREAD

**Issue by temochiz-lab** [temochiz-lab/yanokura-2022#19]
jsPsychのプラグインaudio-button-responseの機能では、ボタンが必ず一番上になってしまいます。
https://www.jspsych.org/7.3/plugins/audio-button-response/
![ボタン位置](https://user-images.githubusercontent.com/106083235/181713015-07ed2acc-b0c8-47a1-bdd4-bda753871332.png)

このまま上にボタンを置いておくのと、次への指示をボタンではなくキーにして、「何かキーを押してください」と大きなBの下に表示するのは、どちらが良いでしょうか？

**Comment by Yanokura-TOKIWA** [comment]
キー押しに変更し、文をBの下に表示する方にしていただきたいです。

**Comment by temochiz-lab** [comment]
了解しました。
