### ISSUE TITLE
実験プログラム構想と刺激について

### ISSUE THREAD

**Issue by Yanokura-TOKIWA** [temochiz-lab/yanokura-2022#6]
お世話になっております。矢ノ倉です。
実験プログラムの構想（pptx）と、提示する刺激11種（wav）を作成しました。
ドライブのリンクをお送りしますので、お手すきの際にご確認いただけますと幸いです。
よろしくお願いいたします。

https://drive.google.com/drive/folders/1NUQ-dtX5usCDC6jXVIS3lSPn3zHDHa-Z?usp=sharing

**Comment by temochiz-lab** [comment]
パワポわかりやすかったので内容理解できました。
こちらは、回答する時のスライダーは三段階という事で良いでしょうか？

**Comment by temochiz-lab** [comment]
スライダーはこの機能で実現できそうです。 Demoから見れるので確認してみてください。
https://www.jspsych.org/7.2/plugins/html-slider-response/

音声の再生と、次への自動での遷移も
https://www.jspsych.org/7.2/plugins/html-slider-response/
で、できそうです。

大丈夫そうであればプロトタイプの作成に着手しますので、別チケットで切ってあるスケジュール感について教えてください。

**Comment by Yanokura-TOKIWA** [comment]
ありがとうございます。
確認しましたところ、こちらで大丈夫そうです。
ご作成よろしくお願いいたします。
スケジュールについても回答させていただきます。

**Comment by temochiz-lab** [comment]
こちら大丈夫そうなのでチケットクローズします。
