### ISSUE TITLE
結果の表示の仕方についての質問

### ISSUE THREAD

**Issue by Yanokura-TOKIWA** [temochiz-lab/yanokura-2022#7]
刺激の速さについて、スライダー（左側：遅い　　中央：同じ　　右側：速い）での回答を現在考えております。
この場合、試行それぞれの結果はどのように表示されるのでしょうか。

**Comment by temochiz-lab** [comment]
本番の実験時は画面表示でなく、CSVファイルに出力しますが、
該当する行と列には、遅い/同じ/速い、と日本語で入ります。
(数字に置き換えて記録もできるのですが、Excelで置換一発でできるので、そっちでいいかなと)

**Comment by Yanokura-TOKIWA** [comment]
ご返信ありがとうございます。
結果の出力に関して理解いたしました。

**Comment by temochiz-lab** [comment]
大丈夫そうなのでチケットをクローズします。
