### ISSUE TITLE
音量の調整についての質問

### ISSUE THREAD

**Issue by Yanokura-TOKIWA** [temochiz-lab/yanokura-2022#8]
実験参加者それぞれに、聴き取りやすい音量を自身で調整してもらおうと考えております。
プログラム内で音量を調整することは可能でしょうか。
それとも、実験開始前に別途調整を行うほうがよろしいでしょうか。

**Comment by temochiz-lab** [comment]
jsPsychの機能的な制約もあって、不可能ではないものの、わかりにくくて調整しにくいものになりそうです。
なので、実験のプログラムと関係無くボリュームの操作をするのが良さそうです。
この時、参加者の立場で一番わかりやすくて簡単そうなのは、スピーカーのボリュームを手で調整してもらう方法だと思います。

**Comment by Yanokura-TOKIWA** [comment]
ご返信ありがとうございます。
音量の調整は実験とは別に行う方が良さそうなのですね。
実験の直前に参加者の手で調整してもらい、参加者毎の音量をこちらで記録していきたいと思います。

**Comment by temochiz-lab** [comment]
PC用のスピーカーで音量をデジタル表示できるスピーカー、ちょっと探してみましたが見つかりませんでした、、

実験室がPhilipsのディスプレイだったと思うのですが、スピーカー付いていたかどうか確認お願いできますでしょうか？
で、スピーカー付きだった場合でも、ディスプレイでの表示はメニューで辿り着くまでに手間だったり調整がめんどうなのがありがちなので、一旦おおまかに設定しておいて、PC側で微調整するのが良いと思いました。
![PC側調整](https://user-images.githubusercontent.com/106083235/179925613-94998155-3e5f-4fa5-b50b-98044fd69e25.png)

**Comment by Yanokura-TOKIWA** [comment]
ディスプレイを確認いたしました。
スピーカーは内蔵されており、ディスプレイ裏のボタンから一操作で音量調整を行うことが可能でした。PCと同じように1ずつ整数値での表示となります。
ただ、ボタンを押す向きによっては他のメニューが出てしまうので、仰るようにPC側で微調整を行う方が分かりやすく安全そうです。

また、音量は騒音計でも計測する予定です。

**Comment by temochiz-lab** [comment]
了解しました。
大丈夫そうなのでチケットクローズします。
