### ISSUE TITLE
実験までのスケジュールについて

### ISSUE THREAD

**Issue by temochiz-lab** [temochiz-lab/yanokura-2022#9]
実験の実施日と、そこから逆算してプログラムのプロトタイプのレビュー日はいつ頃が良いでしょうか？
こちらは8月8日週であれば準備できそうです。

**Comment by Yanokura-TOKIWA** [comment]
10月中下旬に実験を開始したいと考えております。
8月下旬から9月初頭の、8月22日週または8月29日週にレビュー日を設定したいのですが、いかがでしょうか？

**Comment by temochiz-lab** [comment]
22日週は、月、火、が調整可能、
29日週は、火が調整可能になります。

**Comment by Yanokura-TOKIWA** [comment]
ありがとうございます。8/30(火)にお時間をいただきたいです。

レビューは防音室で実際のように行う形でしょうか、それともZoomを用いてでしょうか？

**Comment by temochiz-lab** [comment]
実機でやりましょう。
渡辺先生と相談して時間を決めてもらって良いでしょうか？

**Comment by Yanokura-TOKIWA** [comment]
承知しました。
時間帯の決定と防音室使用についての確認後、再度ご連絡いたします。

**Comment by Yanokura-TOKIWA** [comment]
LINEにて渡辺先生が送ってくださりましたが、
［8/30(火) 13:30〜］になります。
どうぞよろしくお願いいたします。

**Comment by temochiz-lab** [comment]
了解しました。　チケットクローズします。
